# This is the file to instruct Travis CI what to do with the project
# 1. Request a copy of docker
# 2. Build the docker image
# 3. Run the test
# 4. Deploy the code

# we need super user level permission
sudo: required
# tell travis ci that we need a copy of docker
services:
    - docker
# series of steps that need to run before the test is run 
before_install:
    - docker build -t devsoulsearcher/docker-angular -f docker/Dockerfile.dev .

# series of commands that are need to run the test
# -- --coverage : this will automatically close the test execution once done
script:
    - docker run devsoulsearcher/docker-angular npm run test